In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
import numpy as np
import pandas as pd
import edhec_risk_kit as erk

In [2]:
ind=erk.get_ind_returns()
er=erk.annualize_rets(ind["2013":"2017"],12)
cov=ind["2013":"2017"].cov()

In [6]:
l = ["Books","Steel","Oil","Mines"]
erk.msr(0.1, er[l], cov.loc[l,l])

array([0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 2.04957579e-15])

In [7]:
n=er[l].shape[0]
1/n

0.25

In [8]:
erk.gmv(cov.loc[l,l])

array([0.47702487, 0.        , 0.43411202, 0.08886311])

In [12]:
w_msr=erk.msr(0.1, er[l], cov.loc[l,l])
volmat_msr_2018=ind["2018"][l].cov()
pvol_msr_2018=erk.portfolio_vol(w_msr,volmat_msr_2018)
apvol_msr_2018=pvol_msr_2018*(12**0.5)
apvol_msr_2018

0.21983988181484201

In [13]:
w_gmv=erk.gmv(cov.loc[l,l])
volmat_gmv_2018=ind["2018"][l].cov()
pvol_gmv_2018=erk.portfolio_vol(w_gmv,volmat_gmv_2018)
apvol_gmv_2018=pvol_gmv_2018*(12**0.5)
apvol_gmv_2018

0.18973734497775954

In [14]:
w_msr

array([0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 2.04957579e-15])

In [15]:
w_gmv

array([0.47702487, 0.        , 0.43411202, 0.08886311])